### ISSUE TITLE
readme says project is currently being reworked but most recent commit is over a year ago

### ISSUE THREAD

**Issue by qpwo** [NivenT/Evolving_Organisms#1]

**Comment by NivenT** [comment]
Yeah.. the readme is wrong; this project is pretty dead. It was being reworked but most of the changes I was making were simultaneously making the code more complex and the program less successful (If memory serves, the best performing version of the program is [this one](https://github.com/NivenT/Evolving_Organisms/tree/345ff8f4f02f2f25377e7b5499a70179aad84c97)).
